name: e_markety_client
description: Mobile version fo EMarkety project

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_modular: ^5.0.3
  cupertino_icons: ^1.0.5
  timelines: ^0.1.0
  syncfusion_flutter_sliders: ^20.3.48
  syncfusion_flutter_core: ^20.3.48
  intl: ^0.17.0
  flutter_slidable: ^2.0.0
  dio: ^4.0.6
  dartz: ^0.10.1
  flutter_bloc: ^8.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  very_good_analysis: ^3.1.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/static/Raleway-Black.ttf
          weight: 900
        - asset: assets/fonts/static/Raleway-Bold.ttf
          weight: 700
        - asset: assets/fonts/static/Raleway-Medium.ttf
          weight: 500
        - asset: assets/fonts/static/Raleway-Regular.ttf
          weight: 400
        - asset: assets/fonts/static/Raleway-Light.ttf
          weight: 300
        - asset: assets/fonts/static/Raleway-Thin.ttf
          weight: 100
