name: e_markety_client
description: Mobile version fo EMarkety project

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_modular: ^5.0.3
  cupertino_icons: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/static/Raleway-Black.ttf
        - asset: assets/fonts/static/Raleway-Bold.ttf
        - asset: assets/fonts/static/Raleway-Medium.ttf
        - asset: assets/fonts/static/Raleway-Regular.ttf
        - asset: assets/fonts/static/Raleway-Light.ttf
        - asset: assets/fonts/static/Raleway-Thin.ttf
