name: e_markety_client
description: Mobile version fo EMarkety project

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_modular: ^5.0.3
  cupertino_icons: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/static/Raleway-Black.ttf
          weight: 900
        - asset: assets/fonts/static/Raleway-Bold.ttf
          weight: 700
        - asset: assets/fonts/static/Raleway-Medium.ttf
          weight: 500
        - asset: assets/fonts/static/Raleway-Regular.ttf
          weight: 400
        - asset: assets/fonts/static/Raleway-Light.ttf
          weight: 300
        - asset: assets/fonts/static/Raleway-Thin.ttf
          weight: 100
