package br.edu.utfpr.e_markety.model.enums;

// CREATE TYPE status_pedido_enum AS ENUM ('PENDENTE', 'REALIZADO', 'CONFIRMADO', 'PRONTO_PARA_RETIRADA', 'PRONTO_PARA_ENTREGA', 'SAIU_PARA_ENTREGA', 'ENTREGUE');
public enum StatusPedido {
    PENDENTE,
    REALIZADO,
    CONFIRMADO,
    PRONTO_PARA_RETIRADA,
    PRONTO_PARA_ENTREGA,
    SAIU_PARA_ENTREGA,
    ENTREGUE
}
